apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- vars.yaml

commonAnnotations:
  exclude.release.openshift.io/internal-openshift-hosted: "true"
  include.release.openshift.io/self-managed-high-availability: "true"

patches:
# Common configuration for CAPI controller workloads
- target:
    group: apps
    version: v1
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ignored
    spec:
      template:
        metadata:
          annotations:
            # https://github.com/openshift/enhancements/blob/master/enhancements/workload-partitioning/wide-availability-workload-partitioning.md
            target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        spec:
          priorityClassName: "system-cluster-critical"

# Providers should not create namespaces
- target:
    version: v1
    kind: Namespace
  patch: |-
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: ignored

replacements:
# Set resources and limits on all containers
# https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits
- source:
    version: v1
    kind: ConfigMap
    name: kustomize-capi-vars
    fieldPath: data.controllerResources
  targets:
  - select:
      group: apps
      version: v1
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.*.resources
    options:
      create: true
