apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  topology:
    class: dev-test
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
