name: Build CAPO supported images
on:
  schedule:
    # run on Monday at 7
    - cron:  '0 7 * * 1'
  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes_version: ["1.25", "1.26"]
        os: ["flatcar", "ubuntu-2004"]
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          make ${{ matrix.os }}-${{ matrix.kubernetes_version }}
      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: image-builder-images
          path:
            docker-output/
